### ISSUE TITLE
m2crypto throws a segfault on MAC OS X

### ISSUE THREAD

**Issue by tarekziade** [mozilla/PyVEP#3]
``` python
>>> import vep
>>> vep.DummyVerifier.make_assertion("t@m.com", "http://e.com")
Segmentation fault: 11
```

It happens on the dsa128 sign() call,  but if I take the digest that fails with vep and do a manual sign, it works:

``` python
>>> from M2Crypto import DSA
>>> digest = '~A\xd8\xaa\xec\x02\xf5\xfb\x92\xb44\x87\x1c<\xa9:\xba\xa2\xd4J'
>>> dsa = DSA.gen_params(1024)
>>> dsa.gen_key()
>>> dsa.sign(digest)
('\x00\x00\x00\x14.\xe4\x16\x0f\x98\xa3Jb\xfd\xf1\xc0x_\x08\xfdy\x15\x153\xd6', '\x00\x00\x00\x15\x00\xda\x98i\x8c\xfdR\xe7\x157-\xdb\x8d?7\xb7FF\xf6\x13o')
```

So it looks like an issue in the way we initialize the key, but I am not sure what

**Comment by tarekziade** [comment]
Maybe it's related to the SWIG version

under debian the same code works and it has SWIG Version 1.3.40
Mac os x has  SWIG Version 2.0.4  (Configured options: +pcre)

**Comment by tarekziade** [comment]
It fails with the mac os x build found at http://chandlerproject.org/Projects/MeTooCrypto

**Comment by tarekziade** [comment]
reproduced by Toby on his mac os

**Comment by tarekziade** [comment]
downgrading swig to 1.3.40 under mac os x and rebuilding m2crypto has the same effect

**Comment by rfk** [comment]
Thanks Tarek, I finally tracked this down to some sloppy pointer use in the ctypes monkeypatching.  The 64-bit pointers were being truncated to 32 bits.
